export * from './messages';

export const USER_TYPE_TUTOR = 'USER_TYPE:TUTOR';
export const USER_TYPE_PARENT = 'USER_TYPE:PARENT';
export const APPLY_FOR_JOBS = 'APPLY_FOR_JOBS';
export const VIEW_EDIT_PROFILE = 'VIEW_EDIT_PROFILE';
export const TUTOR_BACK = 'BACK:TUTOR';

export const PROFILE_GROUP = 'PROFILE_GROUP';
export const PROFILE_NAME = 'PROFILE_NAME';
export const PROFILE_EMAIL = 'PROFILE_EMAIL';
export const PROFILE_AGE = 'PROFILE_AGE';
export const PROFILE_AGE_YEAR = 'PROFILE_AGE_YEAR';
export const PROFILE_AGE_MONTH = 'PROFILE_AGE_MONTH';
export const PROFILE_AGE_DAY = 'PROFILE_AGE_DAY';

export const PROFILE_EXPERIENCE = 'PROFILE_EXPERIENCE';
export const PROFILE_GENDER = 'PROFILE_GENDER';
export const GENDER_MALE = 'GENDER:MALE';
export const GENDER_FEMALE = 'GENDER:FEMALE';

export const PROFILE_RACE = 'PROFILE_RACE';
export const PROFILE_CITIZENSHIP = 'PROFILE_CITIZENSHIP';
export const PROFILE_QUALIFICATION = 'PROFILE_QUALIFICATION';
export const PROFILE_COVER = 'PROFILE_COVER';
export const PROFILE_PICTURE = 'PROFILE_PICTURE';
export const PROFILE_JOB_CATEGORY = 'PROFILE_JOB_CATEGORY';
export const PROFILE_JOB_PREFERENCE = 'PROFILE_JOB_PREFERENCE';
export const PROFILE_LOCATION_PREFERENCE = 'PROFILE_LOCATION_PREFERENCE';

export const PROFILE_DONE = 'PROFILE_DONE';

export const COMMAND_NAME = 'COMMAND_NAME';
export const COMMAND_EMAIL = 'COMMAND_EMAIL';
export const COMMAND_QUALIFICATION = 'COMMAND_QUALIFICATION';
export const COMMAND_COVER = 'COMMAND_COVER';
export const COMMAND_HP = 'COMMAND_HP';
